name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Print version
        run: swift --version

      - name: Build
        run: swift build --verbose

  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          path: Project

      - name: Checkout SwiftFormat
        uses: actions/checkout@v2
        with:
          repository: nicklockwood/SwiftFormat
          ref: 0.45.6
          path: SwiftFormat

      - name: Run linter
        run: ./SwiftFormat/CommandLineTool/swiftformat --lint ./Project
